name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Youth ITUTE
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@1.4.0
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        # build_configuration: staging
        base_href: /youth-itute/
        deploy_branch: gh-pages
        angular_dist_build_folder: dist/youth-itute # The folder where your project is supposed to be after running ng build by the action.

permissions:
  contents: write # Allow write permission to GITHUB_TOKEN to commit to deploy branch.
